### ISSUE TITLE
make selective ac more flexible.

### ISSUE THREAD

**Issue by lchu-ibm** [foundation-model-stack/fms-fsdp#56]
The current design of selective ac is to checkpoint one block every k blocks:
K=1 (i.e. full ac): ac, ac, ac, ac, ... 
K=2: ac, no-ac, ac, no-ac, ac, no-ac, ...
K=3: ac, no-ac, no-ac,  ac, no-ac, no-ac, ...
...
K=100: this is essentially no-ac for the whole model if num_layer < 100

The granularity is finer and finer towards no-ac side, thus this favor smaller models as we can carefully tune K to achieve the best perf while pushing memory to the limit.

However, what's obviously missing here is the granularity on the other end - as we move towards full ac, the granular is pretty bad: there are enough spaces to further tune between K=1 and K=2, K=2 and K=3, etc.  e.g. what if we want to do things like: 
K=2/3: checkpoint 2 blocks every 3 blocks, i.e.   ac, ac, no-ac, ac, ac, no-ac, ... .

such "fractional k" can be beneficial for larger models as larger models almost always need near-full-ac. so we need full-ac side finer granularity.

To achieve this, we can change K from integer to a tuple (m, n), and instead of doing:
```python
if block_idx % k == 0: ac
else: no-ac
```
we do
```python
if block_idx % n in range(0, m): ac
else: no-ac
```

This way, we can achieve arbitrary selective ac.

Will push a PR soon.

**Comment by lchu-ibm** [comment]
cc @raghukiran1224 @nairbv @daviswer

**Comment by daviswer** [comment]
We may also want to consider (perhaps not for this PR) enabling AC for particular sublayers in addition to "n every k" layers - in particular I recall a substantial performance difference between checkpointing feedforward layers vs attention layers

**Comment by lchu-ibm** [comment]
@daviswer for in-block selectivity, it is coming from torch in a more native implementation in the near future.

**Comment by nairbv** [comment]
general question: is checkpointing the first block considered optimal? For some reason I thought we started checkpointing at the n'th block.

**Comment by lchu-ibm** [comment]
@nairbv shouldn't matter much, if any.

depending on we were doing 0th index or 1th index, we might have done either 0th or nth.   

New method is doing in a more evenly spaced way.

**Comment by nairbv** [comment]
@lchu-ibm maybe my understanding is wrong here but what I mean is...

let's say we have 30 layers. if we checkpoint at layer 10 and 20, then we're saving activations twice. from any given layer, we at most need to recompute from 10 layers back, and on average might be recomputing 5. The net benefit of the checkpoint at layer 10 is that a computation at layer 10+N requires recomputing N layers instead of 10+N layers.

if instead we checkpointed at, say, 2, 12, 22... that first checkpoint at 2 does very little. It's net benefit is that without it we'd only be recomputing 0 and 1 layers to get to 2. The net benefit of a checkpoint at the very start of the model seems smaller? this is why I'd think that we typically want the first of a set of sparse checkpoints to start at layer N not at 0.

Does that makes sense?

**Comment by lchu-ibm** [comment]
@nairbv ah, got it. Let me explain:

ac works on block level, and re-computation only happens on block level too (inside a block). So when we say we want to apply activation recomputation on block K, it means:   for block K, we will discard all intermediate activations and only store the the input/first layer.   And during backward, the whole block will be recomputed to generate all other layers inside this block.

So, it doesn't matter which block we apply ac on, it is always the same impact re. recomputation.

**Comment by nairbv** [comment]
hm... so you mean that the blocks we don't apply it to, by default will save _all_ their activations? i.e. we only avoid saving intermediate activations _within_ a checkpointed block?

**Comment by lchu-ibm** [comment]
@nairbv yes, the namings are always a little confusing, but basically:

apply ac = apply checkpointing = apply re-computation.

no ac = not applying anything = default = all intermediate activations are preserved = no recomputation.


and ac always happen on block level (in our case.).   ac on one block = save one blocks' activations
